version: '3.2'
services:
  postgresdb:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - "5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - PACTBROKER_USER_PASSWORD
      - POSTGRES_PASSWORD
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: 'always'
  pact_broker:
    image: dius/pact-broker
    links:
      - postgresdb
    environment: 
       - "PACT_BROKER_DATABASE_PASSWORD=${PACTBROKER_USER_PASSWORD}"
       - "PACT_BROKER_DATABASE_USERNAME=pactbrokeruser"
       - "PACT_BROKER_DATABASE_HOST=postgresdb"
       - "PACT_BROKER_DATABASE_NAME=pactbroker" 
    ports:
      - "9090:80"
    restart: 'always'
